# Reading the data

In [1]:
import numpy as np
import pandas as pd
df_train=pd.read_csv('E:/Kaggle Competitions/Titanic/train.csv')
df_test=pd.read_csv('E:/Kaggle Competitions/Titanic/train.csv')

# Data preprocessing

In [3]:
df_train.drop(['Name'],axis=1,inplace=True)

In [4]:
df_train.drop(['Cabin'],axis=1,inplace=True)

In [5]:
df_train.drop(['Ticket'],axis=1,inplace=True)

In [6]:
sex={'male':0,'female':1}
embark={'S':0,'C':1,'Q':2,None:1}
df_train.replace({'Sex':sex},inplace=True)
df_train.replace({'Embarked':embark},inplace=True)

In [7]:
mean=df_train['Age'].mean()
age={None:mean}
df_train.replace({'Age':age},inplace=True)

In [8]:
df_train['Age']=df_train['Age'].astype(int)
df_train['Fare']=df_train['Fare'].astype(int)
df_train['Embarked']=df_train['Embarked'].astype(int)

In [9]:
df_train

     PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
0              1         0       3    0   22      1      0     7         0
1              2         1       1    1   38      1      0    71         1
2              3         1       3    1   26      0      0     7         0
3              4         1       1    1   35      1      0    53         0
4              5         0       3    0   35      0      0     8         0
5              6         0       3    0   29      0      0     8         2
6              7         0       1    0   54      0      0    51         0
7              8         0       3    0    2      3      1    21         0
8              9         1       3    1   27      0      2    11         0
9             10         1       2    1   14      1      0    30         1
10            11         1       3    1    4      1      1    16         0
11            12         1       1    1   58      0      0    26         0
12            13         0       3    0   20      0      0     8         0
13            14         0       3    0   39      1      5    31         0
14            15         0       3    1   14      0      0     7         0
15            16         1       2    1   55      0      0    16         0
16            17         0       3    0    2      4      1    29         2
17            18         1       2    0   29      0      0    13         0
18            19         0       3    1   31      1      0    18         0
19            20         1       3    1   29      0      0     7         1
20            21         0       2    0   35      0      0    26         0
21            22         1       2    0   34      0      0    13         0
22            23         1       3    1   15      0      0     8         2
23            24         1       1    0   28      0      0    35         0
24            25         0       3    1    8      3      1    21         0
25            26         1       3    1   38      1      5    31         0
26            27         0       3    0   29      0      0     7         1
27            28         0       1    0   19      3      2   263         0
28            29         1       3    1   29      0      0     7         2
29            30         0       3    0   29      0      0     7         0
..           ...       ...     ...  ...  ...    ...    ...   ...       ...
861          862         0       2    0   21      1      0    11         0
862          863         1       1    1   48      0      0    25         0
863          864         0       3    1   29      8      2    69         0
864          865         0       2    0   24      0      0    13         0
865          866         1       2    1   42      0      0    13         0
866          867         1       2    1   27      1      0    13         1
867          868         0       1    0   31      0      0    50         0
868          869         0       3    0   29      0      0     9         0
869          870         1       3    0    4      1      1    11         0
870          871         0       3    0   26      0      0     7         0
871          872         1       1    1   47      1      1    52         0
872          873         0       1    0   33      0      0     5         0
873          874         0       3    0   47      0      0     9         0
874          875         1       2    1   28      1      0    24         1
875          876         1       3    1   15      0      0     7         1
876          877         0       3    0   20      0      0     9         0
877          878         0       3    0   19      0      0     7         0
878          879         0       3    0   29      0      0     7         0
879          880         1       1    1   56      0      1    83         1
880          881         1       2    1   25      0      1    26         0
881          882         0       3    0   33      0      0     7         0
882          883         0       3    1   22      0      0    10         0
883          884         0       2    0   28      0      0    10         0
884          885         0       3    0   25      0      0     7         0
885          886         0       3    1   39      0      5    29         2
886          887         0       2    0   27      0      0    13         0
887          888         1       1    1   19      0      0    30         0
888          889         0       3    1   29      1      2    23         0
889          890         1       1    0   26      0      0    30         1
890          891         0       3    0   32      0      0     7         2

[891 rows x 9 columns]

# Train test split

In [10]:
from sklearn.model_selection import train_test_split
x=df_train[['PassengerId','Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]
y=df_train[['Survived']]
X_train,X_test,y_train,y_test= train_test_split(x,y,random_state=0)

# K-nn

In [11]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=12)
knn.fit(X_train,y_train)
train_score=knn.score(X_train,y_train)
test_score=knn.score(X_test,y_test)
train_score,test_score

C:\Users\Vatsal pc\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

(0.6736526946107785, 0.7085201793721974)